import React, { useState, useEffect } from "react";
import { useWorker } from "react-web-worker";
import ECharts from "echarts";

const RelationGraph = () => {
  const [graphData, setGraphData] = useState({
    geneNodes: [
      {
        id: "0",
        name: "hsa-mir-1231",
        symbolSize: 20,
        category: 0,
        value: 1,
        geneMirnaRelationship: null,
      },
      {
        id: "1",
        name: "GNAI2",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89405,
          gene: "GNAI2",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "2",
        name: "GNAI2",
        symbolSize: 20,
        category: 2,
        value: 1,
        geneMirnaRelationship: {
          id: 89406,
          gene: "GNAI2",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS27A",
        },
      },
      {
        id: "3",
        name: "PTPN13",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89407,
          gene: "PTPN13",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "4",
        name: "MAPKAPK2",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89408,
          gene: "MAPKAPK2",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "5",
        name: "TRIO",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89409,
          gene: "TRIO",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "6",
        name: "CTNNA1",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89410,
          gene: "CTNNA1",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "7",
        name: "FAM120A",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89411,
          gene: "FAM120A",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "8",
        name: "TMEM131",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89412,
          gene: "TMEM131",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "9",
        name: "ZAK",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89413,
          gene: "ZAK",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "10",
        name: "MYH9",
        symbolSize: 20,
        category: 2,
        value: 1,
        geneMirnaRelationship: {
          id: 89414,
          gene: "MYH9",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS27A",
        },
      },
      {
        id: "11",
        name: "CCP110",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89415,
          gene: "CCP110",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "12",
        name: "AES",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89416,
          gene: "AES",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "13",
        name: "SLC35F5",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89417,
          gene: "SLC35F5",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "14",
        name: "USP34",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89418,
          gene: "USP34",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "15",
        name: "AMPD2",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89419,
          gene: "AMPD2",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "16",
        name: "UAP1",
        symbolSize: 20,
        category: 2,
        value: 1,
        geneMirnaRelationship: {
          id: 89420,
          gene: "UAP1",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS27A",
        },
      },
      {
        id: "17",
        name: "PHF3",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89421,
          gene: "PHF3",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "18",
        name: "CTGF",
        symbolSize: 20,
        category: 2,
        value: 1,
        geneMirnaRelationship: {
          id: 89422,
          gene: "CTGF",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS27A",
        },
      },
      {
        id: "19",
        name: "TRIM25",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89423,
          gene: "TRIM25",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "20",
        name: "ACO1",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89424,
          gene: "ACO1",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "21",
        name: "LIF",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89425,
          gene: "LIF",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "22",
        name: "TRIM28",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89426,
          gene: "TRIM28",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "23",
        name: "TRIM5",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89427,
          gene: "TRIM5",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "24",
        name: "IL6ST",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89428,
          gene: "IL6ST",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "25",
        name: "ETS1",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89429,
          gene: "ETS1",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "26",
        name: "G3BP1",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89430,
          gene: "G3BP1",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "27",
        name: "MKI67",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89431,
          gene: "MKI67",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "28",
        name: "ADM",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89432,
          gene: "ADM",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "29",
        name: "MBNL1",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89433,
          gene: "MBNL1",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "30",
        name: "DDAH1",
        symbolSize: 20,
        category: 2,
        value: 1,
        geneMirnaRelationship: {
          id: 89434,
          gene: "DDAH1",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS27A",
        },
      },
      {
        id: "31",
        name: "AZIN1",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89435,
          gene: "AZIN1",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "32",
        name: "ELMSAN1",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89436,
          gene: "ELMSAN1",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "33",
        name: "LY6K",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89437,
          gene: "LY6K",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "34",
        name: "FAM208A",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89438,
          gene: "FAM208A",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "35",
        name: "COL1A2",
        symbolSize: 20,
        category: 2,
        value: 1,
        geneMirnaRelationship: {
          id: 89439,
          gene: "COL1A2",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS27A",
        },
      },
      {
        id: "36",
        name: "TSC1",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89440,
          gene: "TSC1",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "37",
        name: "AXL",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89441,
          gene: "AXL",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "38",
        name: "CALR",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89442,
          gene: "CALR",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "39",
        name: "TUBB4B",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89443,
          gene: "TUBB4B",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "40",
        name: "DAPK1",
        symbolSize: 20,
        category: 2,
        value: 1,
        geneMirnaRelationship: {
          id: 89444,
          gene: "DAPK1",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS27A",
        },
      },
      {
        id: "41",
        name: "MGEA5",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89445,
          gene: "MGEA5",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "42",
        name: "CHAMP1",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89446,
          gene: "CHAMP1",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "43",
        name: "FAM127B",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89447,
          gene: "FAM127B",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "44",
        name: "RNF103",
        symbolSize: 20,
        category: 1,
        value: 1,
        geneMirnaRelationship: {
          id: 89448,
          gene: "RNF103",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS5",
        },
      },
      {
        id: "45",
        name: "EIF6",
        symbolSize: 20,
        category: 2,
        value: 1,
        geneMirnaRelationship: {
          id: 89449,
          gene: "EIF6",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS27A",
        },
      },
      {
        id: "46",
        name: "HIST1H2BO",
        symbolSize: 20,
        category: 2,
        value: 1,
        geneMirnaRelationship: {
          id: 89450,
          gene: "HIST1H2BO",
          mirnaName: "hsa-miR-1231",
          publication: "Balakrishnan I  et al. 2014",
          methods: "IP",
          tissue: "Bone Marrow",
          cellLine: "HS27A",
        },
      },
    ],
    links: [
      {
        source: "1",
        target: "0",
      },
      {
        source: "2",
        target: "0",
      },
      {
        source: "3",
        target: "0",
      },
      {
        source: "4",
        target: "0",
      },
      {
        source: "5",
        target: "0",
      },
      {
        source: "6",
        target: "0",
      },
      {
        source: "7",
        target: "0",
      },
      {
        source: "8",
        target: "0",
      },
      {
        source: "9",
        target: "0",
      },
      {
        source: "10",
        target: "0",
      },
      {
        source: "11",
        target: "0",
      },
      {
        source: "12",
        target: "0",
      },
      {
        source: "13",
        target: "0",
      },
      {
        source: "14",
        target: "0",
      },
      {
        source: "15",
        target: "0",
      },
      {
        source: "16",
        target: "0",
      },
      {
        source: "17",
        target: "0",
      },
      {
        source: "18",
        target: "0",
      },
      {
        source: "19",
        target: "0",
      },
      {
        source: "20",
        target: "0",
      },
      {
        source: "21",
        target: "0",
      },
      {
        source: "22",
        target: "0",
      },
      {
        source: "23",
        target: "0",
      },
      {
        source: "24",
        target: "0",
      },
      {
        source: "25",
        target: "0",
      },
      {
        source: "26",
        target: "0",
      },
      {
        source: "27",
        target: "0",
      },
      {
        source: "28",
        target: "0",
      },
      {
        source: "29",
        target: "0",
      },
      {
        source: "30",
        target: "0",
      },
      {
        source: "31",
        target: "0",
      },
      {
        source: "32",
        target: "0",
      },
      {
        source: "33",
        target: "0",
      },
      {
        source: "34",
        target: "0",
      },
      {
        source: "35",
        target: "0",
      },
      {
        source: "36",
        target: "0",
      },
      {
        source: "37",
        target: "0",
      },
      {
        source: "38",
        target: "0",
      },
      {
        source: "39",
        target: "0",
      },
      {
        source: "40",
        target: "0",
      },
      {
        source: "41",
        target: "0",
      },
      {
        source: "42",
        target: "0",
      },
      {
        source: "43",
        target: "0",
      },
      {
        source: "44",
        target: "0",
      },
      {
        source: "45",
        target: "0",
      },
      {
        source: "46",
        target: "0",
      },
    ],
    categories: [
      {
        name: "MiRNA: hsa-mir-1231",
      },
      {
        name: "HS5",
      },
      {
        name: "HS27A",
      },
    ],
  });

  const worker = useWorker("./worker.js");

  // 向worker发送消息
  worker.postMessage({
    type: "relationData",
  });

  // 监听worker返回的消息
  worker.onmessage = ({ data }) => {
    setGraphData(data.relationData);
  };

  // 初始化echarts
  useEffect(() => {
    const myChart = ECharts.init(document.getElementById("relationGraph"));
    myChart.setOption({
      title: {
        text: "Relation Graph",
      },
      series: [
        {
          type: "graph",
          layout: "force",
          data: graphData,
          links: graphData.links,
          roam: true,
          label: {
            normal: {
              show: true,
            },
          },
          force: {
            repulsion: 100,
          },
        },
      ],
    });
  }, [graphData]);

  return (
    <div className="h-full w-full">
      <div id="relationGraph" className=" h-full w-full" />
    </div>
  );
};

export default RelationGraph;
